### ISSUE TITLE
Won't Hack NASA

### ISSUE THREAD

**Issue by Zer0-Official** [GooglyTank/Hack-NASA#1]
The program is not hacking NASA. I've left my computer on for 2 days straight running this program. We actually ran out of electricity so I had to borrow my neighbor's generator and let it run for another 14 hours. The government keeps counter-hacking me so it keeps failing. Is there any way to make it stronger?

**Comment by GooglyTank** [comment]
Sorry for our bad job.. if you want you strogner results please buy our preiumium hack nasa service coming out soon thank you

**Comment by Zer0-Official** [comment]
Sorry for my impatience, but when will the premium hack NASA service come out?

**Comment by GooglyTank** [comment]
> Sorry for my impatience, but when will the premium hack NASA service come out?

The PREMIUM -trademarked- hack nasa service is comeing out on my birthday

**Comment by Zer0-Official** [comment]
> The PREMIUM -trademarked- hack nasa service is comeing out on my birthday

When would that be?
